### ISSUE TITLE
Crash on Latin1 in IRC buffer

### ISSUE THREAD

**Issue by meskarune** [jaraco/irc#101]
When using this library my bot crashes whenever latin1 is entered into an irc channel.

```
Traceback (most recent call last):
  File "autobot.py", line 387, in <module>
    main()
  File "autobot.py", line 384, in main
    bot.start()
  File "autobot.py", line 68, in start
    super().start()
  File "/usr/home/meskarune/virtualenv/optimus-outdated/lib/python3.4/site-packages/irc/bot.py", line 328, in start
    super(SingleServerIRCBot, self).start()
  File "/usr/home/meskarune/virtualenv/optimus-outdated/lib/python3.4/site-packages/irc/client.py", line 1249, in start
    self.reactor.process_forever()
  File "/usr/home/meskarune/virtualenv/optimus-outdated/lib/python3.4/site-packages/irc/client.py", line 278, in process_forever
    self.process_once(timeout)
  File "/usr/home/meskarune/virtualenv/optimus-outdated/lib/python3.4/site-packages/irc/client.py", line 259, in process_once
    self.process_data(i)
  File "/usr/home/meskarune/virtualenv/optimus-outdated/lib/python3.4/site-packages/irc/client.py", line 216, in process_data
    c.process_data()
  File "/usr/home/meskarune/virtualenv/optimus-outdated/lib/python3.4/site-packages/irc/client.py", line 579, in process_data
    for line in self.buffer:
  File "/usr/home/meskarune/virtualenv/optimus-outdated/lib/python3.4/site-packages/jaraco/stream/buffer.py", line 104, in lines
    self.handle_exception()
  File "/usr/home/meskarune/virtualenv/optimus-outdated/lib/python3.4/site-packages/jaraco/stream/buffer.py", line 102, in lines
    yield line.decode(self.encoding, self.errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 68: invalid continuation byte
```

My bot's code: [https://github.com/meskarune/autobot]

I'm not entirely sure if this is an issue with my bot or irc lib.

It would be awesome if utf-8 were default and then latin1 used as a backup encoding for irc messages.

**Comment by jaraco** [comment]
See [Decoding Input](https://github.com/jaraco/irc#decoding-input) in the readme for rationale for the current behavior and instructions on how to achieve the behavior your desire.

**Comment by meskarune** [comment]
Thanks for getting back to me so quickly with an answer.
