### ISSUE TITLE
Publish 15.0.5 on PyPI

### ISSUE THREAD

**Issue by sbraz** [jaraco/irc#121]
Since PyPI only has up to 15.0.4 right now.

**Comment by jaraco** [comment]
Seems [the deploy failed](https://travis-ci.org/jaraco/irc/jobs/176119877) due to kennethreitz/requests#3685. I'll restart that job now that it's been fixed.

**Comment by jaraco** [comment]
For posterity, here's the output in the deploy step where the failure occurred:

```
creating build/bdist.linux-x86_64/wheel/irc-15.0.5.dist-info/WHEEL

Traceback (most recent call last):

  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/requests_toolbelt/_compat.py", line 49, in <module>

    from requests.packages.urllib3.contrib import appengine as gaecontrib

  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/requests/packages/urllib3/contrib/appengine.py", line 45, in <module>

    from urlparse import urljoin

ImportError: No module named 'urlparse'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/home/travis/virtualenv/python3.5.2/bin/twine", line 7, in <module>

    from twine.__main__ import main

  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/twine/__main__.py", line 20, in <module>

    from twine.cli import dispatch

  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/twine/cli.py", line 23, in <module>

    import requests_toolbelt

  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/requests_toolbelt/__init__.py", line 12, in <module>

    from .adapters import SSLAdapter, SourceAddressAdapter

  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/requests_toolbelt/adapters/__init__.py", line 12, in <module>

    from .ssl import SSLAdapter

  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/requests_toolbelt/adapters/ssl.py", line 16, in <module>

    from .._compat import poolmanager

  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/requests_toolbelt/_compat.py", line 51, in <module>

    from urllib3.contrib import appengine as gaecontrib

ImportError: No module named 'urllib3'

/home/travis/build/jaraco/irc/.eggs/setuptools_scm-1.15.0-py3.5.egg/setuptools_scm/git.py:56: UserWarning: "/home/travis/build/jaraco/irc" is shallow and may cause errors

running upload_docs

Upload_docs command is deprecated. Use RTD instead.

creating build/docs

error: no files found in upload directory 'build/docs'

No stash found.
```

**Comment by sbraz** [comment]
Wow I didn't think requests had such bugs, thanks for fixing it :)

**Comment by jaraco** [comment]
Replacement job completed, and release should be in PyPI.
