### ISSUE TITLE
UTF-8 error decoding

### ISSUE THREAD

**Issue by DarkSkull91** [jaraco/irc#141]
Hi, I receive this error when I try to execute the **irccat.py** script to connect to the server irc.openjoke.net.

```WARNING:jaraco.stream.buffer:
Unknown encoding encountered. See 'Decoding Input'
in https://pypi.python.org/pypi/irc for details.

Traceback (most recent call last):
  File "./irccat.py", line 80, in <module>
    main()
  File "./irccat.py", line 76, in main
    reactor.process_forever()
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 273, in process_forever
    consume(infinite_call(one))
  File "/usr/local/lib/python2.7/dist-packages/more_itertools/recipes.py", line 159, in consume
    deque(iterator, maxlen=0)
  File "/usr/local/lib/python2.7/dist-packages/jaraco/itertools.py", line 408, in <genexpr>
    return (f() for _ in itertools.repeat(None))
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 254, in process_once
    self.process_data(i)
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 218, in process_data
    c.process_data()
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 535, in process_data
    for line in self.buffer:
  File "/usr/local/lib/python2.7/dist-packages/jaraco/stream/buffer.py", line 104, in lines
    self.handle_exception()
  File "/usr/local/lib/python2.7/dist-packages/jaraco/stream/buffer.py", line 102, in lines
    yield line.decode(self.encoding, self.errors)
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe8 in position 57: invalid continuation byte` 
```

**Comment by jaraco** [comment]
This behavior is by design. See the Decoding Input section of the readme.
