### ISSUE TITLE
test test_client.test_version fails irc-8.5

### ISSUE THREAD

**Issue by jaraco** [jaraco/irc#26]
pytest also fails.

work/irc-8.5 $ PYTHONPATH=build/lib/ pytest
going into /mnt/gen2/TmpDir/portage/dev-python/irc-8.5/work/irc-8.5/irc/tests
===========================  test_bot.py  ============================

==========================  test_client.py  ==========================

=========================  test_schedule.py  =========================

no test dir found testing here: /mnt/gen2/TmpDir/portage/dev-python/irc-8.5/work/irc-8.5

---

Ran 0 test cases in 0.07s (0.06s CPU)
All 3 modules OK

well so much for pytest and pytest-runner, the latter of which I've not seen or used before.

work/irc-8.5 $ PYTHONPATH=build/lib/ nosetests

``` python
==================================================================
FAIL: irc.tests.test_client.test_version
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/mnt/gen2/TmpDir/portage/dev-python/irc-8.5/work/irc-8.5/irc/tests/test_client.py", line 14, in test_version
    assert irc.client.VERSION, "8, 5"
AssertionError: No VERSION detected.

----------------------------------------------------------------------
Ran 19 tests in 3.125s

FAILED (failures=1)
```

Not being a test suite writer I've sunk enough time in attempting to jag a correct arg for "No VERSION detected."

What I have however is

work/irc-8.5 $ python -c "from irc.client import VERSION;print(VERSION)"
(8, 5)

which says to me the test needs re-authoring to do something, well, perhaps 'right'.
Anyways.  It also appears in some prior versions.

---
- Bitbucket: https://bitbucket.org/jaraco/irc/issue/26
- Originally reported by: [idella5](http://bitbucket.org/idella5)
- Originally created at: 2013-08-16T15:32:24.252

**Comment by jaraco** [comment]
oh dear, I think I have to back pedal and cancel.

`````` python
/dev-python/irc $ ebuild irc-8.5.ebuild clean test
========================================>>> Source compiled.
 * pypy2_0: running distutils-r1_run_phase python_test
 * python3_2: running distutils-r1_run_phase python_test
 * python3_3: running distutils-r1_run_phase python_test
 * python2_6: running distutils-r1_run_phase python_test
 * python2_7: running distutils-r1_run_phase python_test
...........................................................
----------------------------------------------------------------------
Ran 19 tests in 3.022s

OK
.........
----------------------------------------------------------------------
Ran 19 tests in 3.026s

OK
.........
----------------------------------------------------------------------
Ran 19 tests in 3.024s

OK
.........
----------------------------------------------------------------------
Ran 19 tests in 3.023s

OK
.........
----------------------------------------------------------------------
Ran 19 tests in 3.044s

OK
```.

Running the ebuild with
python_test() {
        nosetests irc/tests || die "Tests failed under ${EPYTHON}"
}

and it passes. I shoulf have tried that first this time, but it ought pass from
work/irc-8.5/. I reallt don't get it, but never mind


----------------------------------------
Original comment by: [idella5](http://bitbucket.org/idella5)
``````

**Comment by jaraco** [comment]
no problem

---

Original comment by: Jason R. Coombs
