### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by GIANTCRAB** [jaraco/irc#4]
Using Python 2, CentOS 64 bit.

I am unable to install it through easy_install or pip install.

```
[root@vpn-us site-packages]# easy_install irc
Searching for irc
Reading http://pypi.python.org/simple/irc/
Best match: irc 12.1.1
Downloading https://pypi.python.org/packages/source/i/irc/irc-12.1.1.zip#md5=cdfcd72dd17134b920b1e8fa56f89d21
Processing irc-12.1.1.zip
Running irc-12.1.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-6Boo6r/irc-12.1.1/egg-dist-tmp-EZRwc9
Traceback (most recent call last):
  File "/usr/bin/easy_install", line 9, in <module>
    load_entry_point('distribute==0.6.10', 'console_scripts', 'easy_install')()
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 1715, in main
    with_ei_usage(lambda:
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 1696, in with_ei_usage
    return f()
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 1719, in <lambda>
    distclass=DistributionWithoutHelpCommands, **kw
  File "/usr/lib64/python2.6/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.6/distutils/dist.py", line 975, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.6/distutils/dist.py", line 995, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 236, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 472, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 502, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 681, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 958, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 947, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python2.6/site-packages/setuptools/sandbox.py", line 29, in run_setup
    lambda: execfile(
  File "/usr/lib/python2.6/site-packages/setuptools/sandbox.py", line 70, in run
    return func()
  File "/usr/lib/python2.6/site-packages/setuptools/sandbox.py", line 31, in <lambda>
    {'__file__':setup_script, '__name__':'__main__'}
  File "setup.py", line 11
    needs_pytest = {'pytest', 'test', 'ptr', 'release'}.intersection(sys.argv)
                            ^
SyntaxError: invalid syntax
```

**Comment by jaraco** [comment]
Indeed, that syntax is only supported in Python 2.7 and later. Support for Python 2.6 was dropped in 10.0. You'll want to get 9.0 or earlier. For example:

```
# easy_install 'irc<10.0dev'
```
