### ISSUE TITLE
irccat / irccat2 fail to load backports.functools_lru_cache on jessie

### ISSUE THREAD

**Issue by jaraco** [jaraco/irc#66]
hi,

ive installed "irc" with pip, but i had to download irc-13.1.tar.gz manually because the scripts/ directory was nowhere to be found.

steps to reproduce:
tar xzf irc-13.1.tar.gz && cd irc-13.1/scripts && python irccat.py

the error comes with python 2.7+, python 3 says wrong syntax

```
#!python

 python irccat2.py 
Traceback (most recent call last):
  File "irccat2.py", line 10, in <module>
    import irc.client
  File "/home/julius/.local/lib/python2.7/site-packages/irc/client.py", line 68, in <module>
    from jaraco.functools import Throttler
  File "/home/julius/.local/lib/python2.7/site-packages/jaraco/functools.py", line 9, in <module>
    from backports.functools_lru_cache import lru_cache
ImportError: No module named backports.functools_lru_cache

```

```
#!python

python irccat.py 
Traceback (most recent call last):
  File "irccat.py", line 14, in <module>
    import irc.client
  File "/home/julius/.local/lib/python2.7/site-packages/irc/client.py", line 68, in <module>
    from jaraco.functools import Throttler
  File "/home/julius/.local/lib/python2.7/site-packages/jaraco/functools.py", line 9, in <module>
    from backports.functools_lru_cache import lru_cache
ImportError: No module named backports.functools_lru_cache

```

---
- Bitbucket: https://bitbucket.org/jaraco/irc/issue/66
- Originally reported by: steven meier
- Originally created at: 2015-09-26T07:52:56.763

**Comment by jaraco** [comment]
The issue lies with [how backports.functools_lru_cache is resolved as a dependency](https://bitbucket.org/jaraco/jaraco.functools/src/666b189f38d913544746ba40f97d1e9f116496c9/setup.py?at=default&fileviewer=file-view-default#setup.py-32:34). The package is required conditionally on the Python version being 2.7. I suspect that the version of pip you have isn't honoring that dependency properly.

I just installed jaraco.functools with pip 7.1.2 and it installed backports.functools_lru_cache as required.

I suspect you either need to upgrade pip or install backports.functools_lru_cache manually (i.e. `pip install backports.functools_lru_cache`).

Let me know if that doesn't solve it.

---

Original comment by: Jason R. Coombs

**Comment by jaraco** [comment]
Thanks very much, installing it manually solved it.
jessis's pip version is 1.5.7. however that came to be.

---

Original comment by: steven meier

**Comment by jaraco** [comment]
see answer 1

---

Original comment by: steven meier
